import Head from "next/head";
import { Header } from "./Header";

export const Layout: React.FC = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
    </div>
  );
};
